version: '3'
services:
 splash:
  image: scrapinghub/splash
  ports:
   - "8050:8050"

 scrapy:
  build:
   context: ./
   dockerfile: scrapy.dockerfile
  depends_on:
   - splash

 postgres:
  image: postgres
  environment:
   POSTGRES_DB: ${DB_DATABASE}
   POSTGRES_USER: ${DB_USERNAME}
   POSTGRESS_PASSORD: ${DB_PASSWORD}
  volumes:
   # - postgresql:/var/lib/postgresql
   - postgresql:/var/lib/postgresql/data
  ports:
   - "54320:5432"