version: '3'
services:
 splash:
  image: scrapinghub/splash
  ports:
   - "8050:8050"

 scrapy:
  build:
   context: ./
   dockerfile: scrapy.dockerfile
  depends_on:
   - splash

 postgres:
  image: postgres
  environment:
   POSTGRES_DB: postgres
   POSTGRES_USER: postgres
   POSTGRESS_PASSORD: postgres
  volumes:
   - ./postgresql:/var/lib/postgresql/data
  ports:
   - "5432:5432"
# volumes:
#  postgresql:
