version: '3'
services:
 splash:
  image: scrapinghub/splash
  ports:
   - "8050:8050"

 scrapy:
  build:
   context: ./
   dockerfile: scrapy.dockerfile
  depends_on:
   - splash

 mysql:
  image: mysql:5.7
  environment:
   MYSQL_DATABASE: ${DB_DATABASE}
   MYSQL_USER: ${DB_USERNAME}
   MYSQL_PASSWORD: ${DB_PASSWORD}
  volumes:
    - ./mysql:/var/lib/mysql
  ports:
   - "3306:3306"